startup:
  initRate: true

spring:
  redis:
    database: 0
    host: rate-redis
    port: 6379
    password:
    timeout: 10000

provider:
  CurrencyLayer:
    enable: true
    username:
    key:
    plan:
  OneForge:
    enable: true
    username:
    key:
    plan:
  EuropeanCentralBank:
    enable: true
  OpenExchangeRates:
    enable: true
    username:
    key:
    plan: