
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 10000

provider:
  CurrencyLayer:
    username:
    key:
    plan:
  OneForge:
    username:
    key:
    plan: